// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXAEToOcw1lIS77IxIs9eyc_8VJ1yh-fg',
    appId: '1:108435347105:web:ba868f43a505666604c2e0',
    messagingSenderId: '108435347105',
    projectId: 'fire-flutter-1101',
    authDomain: 'fire-flutter-1101.firebaseapp.com',
    storageBucket: 'fire-flutter-1101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejc3Dv0pfXovp1eD3GKblEVn-wZYWRQg',
    appId: '1:108435347105:android:a0fa15489e5d461604c2e0',
    messagingSenderId: '108435347105',
    projectId: 'fire-flutter-1101',
    storageBucket: 'fire-flutter-1101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzQt-_lLYbPq1NxMPx_9ewdd8pQZg1ET0',
    appId: '1:108435347105:ios:bcd4d4558407831b04c2e0',
    messagingSenderId: '108435347105',
    projectId: 'fire-flutter-1101',
    storageBucket: 'fire-flutter-1101.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzQt-_lLYbPq1NxMPx_9ewdd8pQZg1ET0',
    appId: '1:108435347105:ios:bcd4d4558407831b04c2e0',
    messagingSenderId: '108435347105',
    projectId: 'fire-flutter-1101',
    storageBucket: 'fire-flutter-1101.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXAEToOcw1lIS77IxIs9eyc_8VJ1yh-fg',
    appId: '1:108435347105:web:b02fb27cf5e9607d04c2e0',
    messagingSenderId: '108435347105',
    projectId: 'fire-flutter-1101',
    authDomain: 'fire-flutter-1101.firebaseapp.com',
    storageBucket: 'fire-flutter-1101.appspot.com',
  );
}
